### ISSUE TITLE
How to make dataset with lmdb type?

### ISSUE THREAD

**Issue by litchi99** [JiaquanYe/MASTER-mmocr#2]
Hello，I downloaded your project's dataset from google driver and trainning successfully.
Now I want to create a little dataset which same as your's. 
Can you provide the code which related to lmdb dataset convert?

**Comment by JiaquanYe** [comment]
You can refer to [this repo](https://github.com/Fangyh09/Image2LMDB)

**Comment by litchi99** [comment]
Thanks! This problem has been solved,
