### ISSUE TITLE
Pretrained model ?

### ISSUE THREAD

**Issue by ThorPham** [JiaquanYe/MASTER-mmocr#3]
Hello, many thanks to your excellent work! I'm not enough resouce to train model from scratch .Can you share me weight by email dungpv.ai@gmail.com . Thank so much.

**Comment by JiaquanYe** [comment]
> Hello, many thanks to your excellent work! I'm not enough resouce to train model from scratch .Can you share me weight by email [dungpv.ai@gmail.com](mailto:dungpv.ai@gmail.com) . Thank so much.

Due to the company’s privacy policy, weighted files will not be released.
